export const CarListData = [
  {
    id: 1,
    name: "Toyota Camry",
    seat: 4,
    desc: "faboulus",
    amount: 10,
    image: "/image/5.png",
  },
  {
    id: 2,
    name: "Comfot",
    seat: 4,
    desc: "extra legroom",
    amount: 12,
    image: "/image/2.png",
  },

  {
    id: 3,
    name: "Bolero",
    seat: 5,
    desc: "extra seat.",
    amount: 13,
    image: "/image/4.png",
  },
  {
    id: 4,
    name: "Swift Dzire",
    seat: 4,
    desc: "Size Big",
    amount: 15,
    image: "/image/car.png",
  },

  {
    id: 5,
    name: "TAXI ",
    seat: 2,
    desc: "with music.",
    amount: 5,
    image: "/image/UberComfort.png",
  },
  {
    id: 6,
    name: "BMW",
    seat: 3,
    desc: "Relax.",
    amount: 14,
    image: "/image/new.png",
  },
  {
    id: 7,
    name: "Volvo",
    seat: 5,
    desc: "good",
    amount: 10,
    image: "/image/pet.png",
  },
  {
    id: 8,
    name: "punch ev",
    seat: 3,
    desc: "with wifi",
    amount: 12,
    image: "/image/44.png",
  },
  {
    id: 9,
    name: "Nano Car",
    seat: 2,
    desc: "reliable",
    amount: 9,
    image: "/image/55.png",
  },
];
